# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-06 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('iservice', '0002_auto_20160703_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='iserviceuser',
            name='name',
            field=models.CharField(default='Teste', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iserviceuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='iserviceuser',
            name='picture',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
