# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-06 01:09
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('iservice', '0003_auto_20160706_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iserviceuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True),
        ),
    ]
