# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-17 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('iservice', '0004_auto_20160706_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=140)),
                ('tags', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('ALIMENTACAO', 'Alimenta\xe7\xe3o'), ('ANIMAIS', 'Animais'), ('AULAS', 'Aulas'), ('AUTOMOTIVO', 'Automotivo'), ('BELEZA_E_BEM_ESTAR', 'Beleza e bem-estar'), ('CASA_E_CONSTRUCAO', 'Casa e constru\xe7\xe3o'), ('COMUNICACAO_E_ARTES', 'Comunica\xe7\xe3o e artes'), ('CONSULTORIA', 'Consultoria'), ('DELIVERY', 'Delivery'), ('EVENTOS_E_MUSICA', 'Eventos e M\xfasica'), ('SAUDE', 'Sa\xfade'), ('TECNOLOGIA', 'Tecnologia'), ('TRANSPORTE', 'Transporte'), ('SEGURANCA', 'Seguran\xe7a'), ('OUTROS', 'Outros')], max_length=60)),
                ('phones', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='iserviceuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iservice.IserviceUser'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iservice.Service'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iservice.IserviceUser'),
        ),
    ]
