# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-17 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iservice', '0006_auto_20160717_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='tags',
        ),
    ]
