# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-20 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iservice', '0008_auto_20160720_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='city',
            new_name='city_db',
        ),
    ]
