# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-09 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iservice', '0010_iserviceuser_favorites_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
