# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-14 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iservice', '0012_evaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='comment',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
