# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-24 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iservice', '0015_evaluation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iservice.Service')),
            ],
        ),
    ]
