# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-19 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iservice', '0017_service_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='latitude',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='longitude',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
