# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-20 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iservice', '0018_auto_20160919_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
    ]
